/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ErrorMessage: typeof import('./src/components/ErrorMessage.vue')['default']
    NoResults: typeof import('./src/components/NoResults.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    PaintingCard: typeof import('./src/components/PaintingCard.vue')['default']
    PaintingsGrid: typeof import('./src/components/PaintingsGrid.vue')['default']
    PaintingsList: typeof import('./src/components/PaintingsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchComponent: typeof import('./src/components/SearchComponent.vue')['default']
    SkeletonLoader: typeof import('./src/components/SkeletonLoader.vue')['default']
    TheCards: typeof import('./src/components/TheCards.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
  }
}
